u_auth/auth_main/urls.py
from django.urls import path
from auth_main import views
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

app_name='auth_main'

urlpatterns = [
    path("",views.index,name="index"),
    path("reg/",views.registartion,name="registartion"),
    path("login/",views.Login_page,name="Login_page"),
    path("userlogout/",views.user_logout,name="user_logout"),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
 

u_auth/u_auth/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('auth_main.urls')),
]

u_auth/auth_main/models.py
from django.db import models
from django.contrib.auth.models import User

class userInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    fb_id= models.URLField(blank=True)
    profile_pic= models.ImageField(upload_to='profile_pic',blank=True)
    
    def __str__(self):
        return self.user.username

        

# Create your models here.

u_auth/auth_main/forms.py
from django import forms
from auth_main.models import  userInfo
from django.contrib.auth.models import User

class userfrom(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields=('username','email','password')


class userInfofrom(forms.ModelForm):
    class Meta():
        model = userInfo
        fields=('fb_id','profile_pic')

u_auth/auth_main/views.py
from auth_main.models import userInfo
from django.shortcuts import render
from django.http import HttpResponse
from auth_main.forms import userfrom,userInfofrom



from django.contrib.auth import authenticate, login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django .urls import reverse
from django.contrib.auth.models import User



def index(request):
    dict={}

    if request.user.is_authenticated:
        current_user=request.user
        user_id=current_user.id
        user_basic_info=User.objects.get(pk=user_id)
        user_moreinfo= userInfo.objects.get(user__pk=user_id)
        dict={'user_basic_info':user_basic_info,'user_moreinfo':user_moreinfo}
    
    return render(request,'index.html',context=dict)

def registartion(request):
    registered=False
    if request.method=='POST':
        user_form=userfrom(data=request.POST)
        user_info= userInfofrom(data=request.POST)

        if user_form.is_valid() and user_info.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            userInfo=user_info.save(commit=False)
            userInfo.user=user
            if 'profile_pic' in request.FILES:
                userInfo.profile_pic=request.FILES['profile_pic']

            userInfo.save()
            registered=True

        
      
    else:
        user_form=userfrom()
        user_info= userInfofrom()
    diction={'user_form':user_form,'user_info':user_info,'register':registered}

    
    return render(request,'registratiom.html',context=diction)


def Login_page(request):
    if request.method=='POST':
        username= request.POST.get('username')
        password= request.POST.get('password')
        print(username)
        print(password)
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('auth_main:index'))
            else:
                return HttpResponse("this  acccount are not active")

        else:
            return HttpResponse("login detais is worng")            

    diction={'name': 'Login Page'}
    return render (request,'Login.html',context=diction)


'''def user_login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        
        print(username)
        print(password)'''

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('auth_main:index'))

u_auth/templates/Login.html
{% extends 'base.html' %}
{% block body %}
<h1>{{name}}</h1>
<br>
<br>
<form  method='POST'>
<label for="username">Username:</label>
<br>
<input type="text" name="username" placeholder="Enter Username.." required class="form-control">
<br><br>

<label for="password">Password:</label>
<br>
<input type="password" name="password" placeholder="Enter password.." required class="form-control">
{% csrf_token %}
<br>
<br>

<input type="submit" name="submit" value='Login' class="btn btn-primary">

</form>

{% endblock body %}

u_auth/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Example</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
      integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js"
      integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <ul class="navbar-nav">
       <li class="nav-item active">
          <a class="nav-link" href="{% url 'auth_main:index' %}">Home</a>
        </li>
      {% if user.is_authenticated %}
         <li class="nav-item ">
          <a class="nav-link" href="{% url 'auth_main:user_logout' %}">Logout</a>
        </li>
      {% else %}  
       
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'auth_main:registartion' %}">Registration</a>
        </li>
         <li class="nav-item ">
          <a class="nav-link" href="{% url 'auth_main:Login_page' %}">Login</a>
        </li>
      {% endif %}  
      </ul>
    </nav>
    <div class="container">{% block body %} {% endblock body %}</div>
  </body>
</html>

u_auth/templates/index.html
{% extends 'base.html' %}
{% block body %}
<h1> this is index page </h1>
{%if user.is_authenticated%}
<p>Hi,{{user_basic_info.username}}</p>
<p> your Email {{user_basic_info.email}}</p>
<p> <a href="{{user_moreinfo.fb_id}}">Faccbook</a> </p>
<image src="/media/{{user_moreinfo.profile_pic}}" width="200px">
{%else%}
<div class="alert alert-primary">You are not Login </div>
{%endif%}


{% endblock body %}

u_auth/templates/registratiom.html
{% extends 'base.html' %}
{% block body %}
<h1> this is registration page </h1>
{% if register %}
<div class="alert alert-success"> registartion successfull </div>
{% else %}
<form  enctype="multipart/form-data" method="POST">

{{user_form.as_p}}
{{user_info.as_p}}
{% csrf_token %}
<input type="submit" name="submit" value="Register">
</form>
{% endif %}

{% endblock body %}